name: CloudFormation Templates

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions: {}

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false

      - name: templates 
        uses: scottbrenner/cfn-lint-action@ed184e91f5085a2932501da8314e899e5e0ef5be # v2.7.1
        with:
          version: "[sarif]>=1.0"
          command: cfn-lint --non-zero-exit-code error -t ./*.yaml
