name: CloudFormation Templates

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions: {}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: templates 
        uses: scottbrenner/cfn-lint-action@c5f18dc4be13042d564f3052f4067dc9ceafe355 # v2.7.0
        with:
          version: "[sarif]>=1.0"
          command: cfn-lint --non-zero-exit-code error -t ./*.yaml
