name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: '1.24.x'
          cache: false

      - name: Set version
        shell: bash
        run: echo "VERSION=$(./tools/version)" >> $GITHUB_ENV

      - name: Build
        run: GOOS=linux CGO_ENABLED=0 go build -o ./main ./...

      - name: Package
        shell: bash
        run: zip "lambda-promtail-$VERSION.zip" main

      - name: AWS Auth Dev
        id: aws-auth-dev
        if: ${{ !startsWith(github.ref, 'refs/tags/v') && github.ref == 'refs/heads/main' }}
        uses: grafana/shared-workflows/actions/aws-auth@85022085ed5314601c05d10e846de56bdd71e369 # aws-auth/v1.0.3
        with:
          aws-region: "us-east-2"
          role-arn: "arn:aws:iam::410348018613:role/github-actions/lambda-promtail-release-write-role"
          pass-claims: "repository_owner, repository_name, job_workflow_ref, ref, event_name"
          set-creds-in-environment: true

      - name: Upload Dev
        if: ${{ !startsWith(github.ref, 'refs/tags/v') && github.ref == 'refs/heads/main' }}
        run: |
          aws s3 cp "lambda-promtail-$VERSION.zip" s3://grafanalabs-dev-cf-templates/lambda-promtail/ --acl public-read
          aws s3 cp lambda-promtail.yaml s3://grafanalabs-dev-cf-templates/cloudwatch-logs/ --acl public-read
          aws s3 cp aws-alb-logs.yaml s3://grafanalabs-dev-cf-templates/logs-with-lambda/ --acl public-read
          aws s3 cp aws-eventbridge-logs.yaml s3://grafanalabs-dev-cf-templates/logs-with-lambda/ --acl public-read

      - name: AWS Auth Prod
        id: aws-auth-prod
        if: startsWith(github.ref, 'refs/tags/v')
        uses: grafana/shared-workflows/actions/aws-auth@85022085ed5314601c05d10e846de56bdd71e369 # aws-auth/v1.0.3
        with:
          aws-region: "us-east-2"
          role-arn: "arn:aws:iam::008923505280:role/github-actions/lambda-promtail-release-write-role"
          pass-claims: "repository_owner, repository_name, job_workflow_ref, ref, event_name"
          set-creds-in-environment: true

      - name: Upload Prod
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          aws s3 cp "lambda-promtail-$VERSION.zip" s3://grafanalabs-cf-templates/lambda-promtail/ --acl public-read
          aws s3 cp lambda-promtail.yaml s3://grafanalabs-cf-templates/cloudwatch-logs/ --acl public-read
          aws s3 cp aws-alb-logs.yaml s3://grafanalabs-cf-templates/logs-with-lambda/ --acl public-read
          aws s3 cp aws-eventbridge-logs.yaml s3://grafanalabs-cf-templates/logs-with-lambda/ --acl public-read
