name: Release

on:
  push:
    branches:
      - main
      - karsten/release # TODO: remove after verifying this workflow works.

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: '1.24.x'
          cache: false

      - name: Set version
        shell: bash
        run: echo "VERSION=$(./tools/version)" >> $GITHUB_ENV

      - name: Build
        run: GOOS=linux CGO_ENABLED=0 go build -o ./main ./...

      - name: Package
        shell: bash
        run: zip "lambda-promtail-$VERSION.zip" main

      - name: AWS Auth Dev
        id: aws-auth
        if: !startsWith(github.ref, 'refs/tags/v')
        uses: grafana/shared-workflows/actions/aws-auth@aws-auth/v1.0.2
        with:
          aws-region: "us-east-2"
          role-arn: "arn:aws:iam::410348018613:role/github-actions/lambda-promtail-release-write-role"
          pass-claims: "repository_owner, repository_name, job_workflow_ref, ref, event_name"
          set-creds-in-environment: true

      - name: Upload Dev
        if: !startsWith(github.ref, 'refs/tags/v')
        run: aws s3 cp "lambda-promtail-$VERSION.zip" s3://grafanalabs-dev-cf-templates/lambda-promtail/ --acl public-read

      - name: AWS Auth Prod
        id: aws-auth
        if: startsWith(github.ref, 'refs/tags/v')
        uses: grafana/shared-workflows/actions/aws-auth@aws-auth/v1.0.2
        with:
          aws-region: "us-east-2"
          role-arn: "arn:aws:iam::<todo>:role/github-actions/lambda-promtail-release-write-role"
          pass-claims: "repository_owner, repository_name, job_workflow_ref, ref, event_name"
          set-creds-in-environment: true

      - name: Upload Prod
        if: startsWith(github.ref, 'refs/tags/v')
        run: aws s3 cp "lambda-promtail-$VERSION.zip" s3://grafanalabs-cf-templates/lambda-promtail/ --acl public-read
